#!/usr/bin/env bash
# Everything that has to hold before a commit. Runs from the pre-commit hook
# and by hand as `pnpm verify`. Quiet unless something fails.
#
# Note this checks the working tree, not the staged snapshot — the usual
# trade-off for a hook that stays fast. A partial commit is the case it cannot
# see.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

run() {
  local label=$1
  shift
  local output
  if output=$("$@" 2>&1); then
    printf '  ok    %s\n' "$label"
  else
    printf '  FAIL  %s\n\n%s\n' "$label" "$output" >&2
    exit 1
  fi
}

run "types   (astro check)" pnpm check
run "lint    (oxlint)" pnpm lint
run "build   (astro build)" pnpm build

# The PDF is committed and regenerated by hand, so nothing else would notice
# it drifting away from the page it is printed from.
expected=$(bash scripts/resume-stamp.sh)
actual=$(cat .resume-stamp 2>/dev/null || true)

if [ "$expected" != "$actual" ]; then
  printf '  FAIL  resume  (public/resume.pdf is stale)\n\n' >&2
  cat >&2 <<'EOF'
The /resume/ page has changed since the PDF was last printed from it.

  pnpm resume && git add public/resume.pdf .resume-stamp

EOF
  exit 1
fi

printf '  ok    resume  (PDF matches the page)\n'
